from __future__ import annotations

from config import (
    EMB_BASE_DIR,
    POSE_EMB_DIR,
    PREPROCESS_ROOT,
    PROCESSED_SPLIT_DIR,
    PROJECT_ROOT,
    SAVED_DIR,
    TEXT_EMB_DIR,
    DEPTH_EMB_DIR,
)


DEFAULT_SAVED_DIR = SAVED_DIR
DEFAULT_PROCESSED_SPLIT_DIR = PROCESSED_SPLIT_DIR
DEFAULT_TEXT_EMB_DIR = TEXT_EMB_DIR
DEFAULT_DEPTH_EMB_DIR = DEPTH_EMB_DIR
DEFAULT_POSE_EMB_DIR = POSE_EMB_DIR
DEFAULT_EMB_BASE_DIR = EMB_BASE_DIR
